CREATE TABLE `sites` (
      `id_site` int (10) unsigned NOT NULL AUTO_INCREMENT,
      `fid_account` int (10) unsigned NOT NULL,
      `site_name` varchar(128) DEFAULT NULL,
      `site_logo` varchar(128) DEFAULT NULL,
      `site_description` varchar(160) DEFAULT NULL,
      `site_url` varchar(255) DEFAULT NULL,
      `site_status` char(4) DEFAULT NULL,
      `site_enforcement` varchar(4) DEFAULT NULL,
      `site_zones` text DEFAULT '[]',
      `site_private` varchar(64) DEFAULT NULL,
      `site_public` varchar(64) DEFAULT NULL,
      `site_domains` text DEFAULT NULL,
      `site_redirect` varchar(256) DEFAULT NULL,
      `site_scopes` text DEFAULT '`["AUTO"]`',
      `site_created` timestamp NULL DEFAULT current_timestamp(),
      `site_updated` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
      `site_testmode` tinyint (4) DEFAULT 1,
      `site_gate_signup` tinyint (4) DEFAULT 1,
      `site_gate_confirm` varchar(256) DEFAULT NULL,
      `site_gate_exit` varchar(256) DEFAULT NULL,
      `site_agent_private` varchar(36) DEFAULT NULL,
      PRIMARY KEY (`id_site`),
      UNIQUE KEY `site_public_UNIQUE` (`site_public`),
      UNIQUE KEY `site_private_UNIQUE` (`site_private`),
      KEY `site_url` (`site_url`),
      KEY `site_status` (`site_status`),
      KEY `fid_account` (`fid_account`),
      KEY `site_public` (`site_public`),
      KEY `site_created` (`site_created`),
      KEY `site_updated` (`site_updated`),
      KEY `site_agent_private` (`site_agent_private`),
      CONSTRAINT `fk_sites_account` FOREIGN KEY (`fid_account`) REFERENCES `accounts` (`id_account`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB AUTO_INCREMENT = 5 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;