CREATE TABLE `sites` (
  `id_site` int NOT NULL AUTO_INCREMENT,
  `fid_account` varchar(36) DEFAULT NULL,
  `site_name` varchar(128) DEFAULT NULL,
  `site_logo` varchar(128) DEFAULT NULL,
  `site_description` varchar(160) DEFAULT NULL,
  `site_url` varchar(255) DEFAULT NULL,
  `site_status` char(4) DEFAULT NULL,
  `site_enforcement` varchar(4) DEFAULT NULL,
  `site_zones` text,
  `site_private` varchar(64) DEFAULT NULL,
  `site_public` varchar(64) DEFAULT NULL,
  `site_domains` text,
  `site_redirect` varchar(256) DEFAULT NULL,
  `site_permissions` text,
  `site_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `site_updated` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `site_testmode` tinyint DEFAULT '1',
  `site_gate_signup` tinyint DEFAULT '1',
  `site_gate_confirm` varchar(256) DEFAULT NULL,
  `site_gate_exit` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`id_site`),
  UNIQUE KEY `site_public_UNIQUE` (`site_public`),
  UNIQUE KEY `site_private_UNIQUE` (`site_private`),
  KEY `site_url` (`site_url`),
  KEY `site_status` (`site_status`),
  KEY `fid_account` (`fid_account`),
  KEY `site_public` (`site_public`),
  KEY `site_created` (`site_created`) /*!80000 INVISIBLE */,
  KEY `site_updated` (`site_updated`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
