export type FaceDirection = "unknown-unknown"
      | "left-center"
      | "right-center"
      | "center-center"
      | "left-top"
      | "right-top"
      | "center-top"
      | "left-bottom"
      | "right-bottom"
      | "center-bottom";